### ISSUE TITLE
status() fail on some device

### ISSUE THREAD

**Issue by jkerdreux-imt** [TradeFace/tuya#24] opened 2020-05-10 09:28 UTC
Hi, 
I just received a Utorch RGB light. I tested with the current code. I managed to get status.

`2020-05-10 11:08:27 i7 tuyaface[150047] DEBUG reply: b'{"devId":"00747018f4cfa262ea13","dps": "1":true,"2":"white","3":255,"4":25,"5":"ff00550154ffff","6":"c479000025ffc3","7":"ffff320100ff00","8":"ffff2003ff000000ff000000ff","9":"ffff2001ff0000","10":"ffff3205ff000000ff00ffff00ff00ff0000ff"}}'
`
Here a sbytes dump off the answer: 

`b'\x00\x00U\xaa\x00\x00\x00\x00\x00\x00\x00\n\x00\x00\x00\xfc\x00\x00\x00\x00\x11\xa6\x9a8\xcdN>L\x0cu\x84\x18\x87\xa6\x0b"\xe4\xfc#{:\x18N>\n\x87\xa1q\xf0*3\r\x17\x8d\xc4\x15\xcc\xc6+\x9e\x80&\xe1">a=\xbe\x8bc\xd6\x1e\xc5\xb4\xdf\xfe\x7f\x9d\x9f\x83\xd3\xb7\xe2\xd5\xbc\xeb\xed\xe9\x00\xbcN]j\x90\xe19\xc9/<\xae\xb8\xe4Dt\xf3]\xc0Kg\x01"\x01*\x11a\x9c\xd3\xac\xf3\x9ah\xd6\x96\xb5\xe4\xd2\xd1\xec\x8b\x04\xe7U\xde\xcd\x88\xf6\xc3nP\xa6\xe6\xf4\xef\x9a\xe1\xe8\xa2!\xb1\xcc\t_\xe5\x03\x1cv\x96E\x9a\x0ccn\x95\x8en\xfd\x9a\xe5\xfc\xe4|U\x07\x8e\xb5U\x04\xd6R\x9e\xfd\x93@\x9e\xcf\'\xd5\xdf3}\xd4A\x9bH|\xc5@\xa5@\x83\xc7\x15\x94\x98!K\x04\r\x08\xf8\xcf\xe0\x9f\xd3\x1c9\xaf\xc6\xa1\xdb\x137u\xdc\x9c\xf9\x19\x0b\x07\xdb\x85Z"\xfe\x8a\xf3\xba\x8f\x0b\xd0NLb\xc9\xeb7\xec\x80.LU5v\xfb\xc8\x1btx\xe6\x0c7\xf4BU\x00\x00\xaaU'`

But when I call status() a second time, I get a ValueError. I tracked down this issue, and found that any subsequent call receive a payload with data length fixed a 0. 

Here is the sbytes array

`b'\x00\x00U\xaa\x00\x00\x00\x00\x00\x00\x00\n\x00\x00\x01\x0c\x00\x00\x00\x00\x11\xa6\x9a8\xcdN>L\x0cu\x84\x18\x87\xa6\x0b"\xe4\xfc#{:\x18N>\n\x87\xa1q\xf0*3\r\xc7*\x8a\xc3r\x16\x17+C\x82\xe6\x11K\x07\xdfo\xa7\x0fy\xf8\x1b\x8e\xf2\xfd\x9d\xdd\x9d\xd5\x01\xf4#p%\xb6hPK$j\xec\xaf\x18kJ\x9eE\xfd\xb5\x89\xe3I8\x19\xc7\x84\xf3\x87\xbb\x03d\x05C%\x07qP\xd9\x81\xd87\x18^\xdc\x96#e\xf8\x9f\x94\xe2\x18\xaa\xbc\xf4\xc2\x8b%\xa8q\xe9\xe1\xcd\x07x\x0e\x13\x07\x81[\x12\xf9\xe6\xc8ba\x18l\xaa\xc5\x80~\xb4\xa3\xebH\xef\xea\x99\x92\x07\x9a\xb9s\xbe\xef\xc8e\xd77\xe1G\x97+\xf1\xfbo\xec\x17\xbf\xd3,Q\x95\xecT\xa1\x04\xf0z\x071\xb1\xbb\xa3V\xcaw\xc5!\xd1k\x0eR\x07\x8b\xc2\xde\x8f\xdc\x1fT\xd6\x8fF\xce\x96\xda\x1fyG=\xdd?|\x8b4\x19\x18\xa2\xe3\xd5\xde\x97\x1c,\x12>\x11\xdan\x19\xb1\x8b\x01K\x91\x84\x9e\xde\x0e${\n\xc9Q\x16v4\x818\x83i\'5\x14A\xdc\x86\x00\x00\xaaU'
`
This code : 
`data = sbytes[20:8+int.from_bytes(sbytes[15:16], byteorder='little')]`

`sbytes[15:16] = 0x0c => sbytes[20:8+12] = []`

Any idea ?

**Comment by jkerdreux-imt** [comment] 2020-05-10 12:32
The issue come from the data size. In this case, it should be 0x10c not 0xc. Actual size take only 2 bytes encoding => max 255 value. The status request on Utorch lamp returns 268 bytes.

**Comment by jkerdreux-imt** [comment] 2020-05-10 12:42
Ok, I get it working. It should be :

`data = sbytes[20:8+int.from_bytes(sbytes[14:16], byteorder='big')]`

Caution, byteorder is 'big' for me, should be fixed in cmd too. 

I gonna finish some tests, and send a pull-request.

**Comment by jkerdreux-imt** [comment] 2020-05-10 13:08
done.

**Comment by TradeFace** [comment] 2020-05-10 22:40
Thanks for the PR. I'll try to merge and test it tomorrow

**Comment by TradeFace** [comment] 2020-05-11 08:40
merged and published as v1.1.5

P.S. your fix on #20 didn't work on one of my devices. I've added another condition. Can you check if that works for you?

**Comment by jkerdreux-imt** [comment] 2020-05-11 10:53
This #20 patch is a bit rough. I think we can write a better one. This looks like a Py3 issue. You test on Py2 or 3 ? with pyaes or pycryptodome ? 

Another weird stuff is the Cryptodome import. Only one crypto API should be ok.

**Comment by TradeFace** [comment] 2020-05-11 11:20
I test with py 3.6 with pycryptodome. The pyaes bit was copied from the original lib. I believe it's a fallback for py2, but never took the time to look into it.

**Comment by TradeFace** [comment] 2020-05-11 11:46
done. in dev branch

**Comment by jkerdreux-imt** [comment] 2020-05-11 12:27
I checked the dev branch, much cleaner :) 

My main concern: 
I have both cryptodome and pyaes installed..but my install still use pyaes because the import is buggy. The pycryptodome module is a replacement to pycrypto, so the import should be

`from Crypto.Cipher import AES  
`
That's why the #20 occurs. I have both cryptodome & pyaes..wrong import => it use pyaes which return a b'' and not a '' .

**Comment by TradeFace** [comment] 2020-05-11 12:51
Okay changed that import on dev. I'm a bit unsure if the Cryptodome lib now actually is used though

```
$ pip3 freeze
...
pycrypto==2.6.1
pycryptodome==3.7.3
pycryptodomex==3.9.7
...
```

**Comment by jkerdreux-imt** [comment] 2020-05-11 13:04
Ok, fine. you can revert the #20 so. no more b'' just plain old string w/ dome

pycrypto was installed on your box thought package system no ? I always use virtualenv to avoid this stuff. 

Note: pyaes was great too. It's having both that cause some issues

**Comment by TradeFace** [comment] 2020-05-11 13:23
Yeah I should use virtualenv too... lazy... 
Pyaes seems unsupported (last update 3y ago).
Anyway dev is updated

**Comment by jkerdreux-imt** [comment] 2020-05-12 21:39
Ok, I run into the same issue you have. cryptodome vs pycrypto. In fact pycrypto is mandatory for a lot of packages (aqara or yeelight for ex). If I install cryptodome and pycrypto  aqara doen't work because of different API between two. I think switching back to pycrypto is the best thing because most packages are compliant w/ cryptodome.

This is a cryptodome issue, using the exact same name wasn't a brilliant idea.

**Comment by TradeFace** [comment] 2020-05-12 21:46
pycryptodomex is independent. So that could be used instead.

**Comment by TradeFace** [comment] 2020-05-12 21:53
updated dev

**Comment by jkerdreux-imt** [comment] 2020-05-12 22:56
#11 is back :) bitstring and Cryptodome ImportError. 

Please remove import tuya from the setup, and simply put author & version in setup.py that's enough

**Comment by TradeFace** [comment] 2020-05-13 07:46
done!

**Comment by jkerdreux-imt** [comment] 2020-05-13 10:23
Fine

I get a new bug w/ the status() introduced w/ the return {} in _select_reply().
```
   reply = _status(device)
   logger.debug("reply: %s", reply) 
   return json.loads(reply)

```
In some condition, `reply = {}` due to `return {}` in _select_reply(). This raise a error in `json.loads(reply) `

```
  File "/home/jkx/tuya/tuyaface/__init__.py", line 205, in status
    return json.loads(reply)
  File "/usr/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not dict
```

**Comment by TradeFace** [comment] 2020-05-13 10:43
Hmmm, I guess that should have been "{}" instead. Kinda strange it doesn't give an error here.

**Comment by jkerdreux-imt** [comment] 2020-05-13 10:49
If you do that, this will break this kind of stuff (already reported) 
```
data = status() 
if data: ... 

```
cause data will always contains something.

**Comment by TradeFace** [comment] 2020-05-13 10:58
No that won't break. json.loads would return an empty dict as intended. 
dev updated

**Closed** 2020-05-14 08:14 UTC
